### ISSUE TITLE
[DMS] Create an empty review payment step

### ISSUE THREAD

**Issue by KoolCards** [GTBitsOfGood/gen-soln#166]
We need to create a review payment step in our donation form as shown in the [Figma](https://www.figma.com/file/HMEsyyl6EGJ4hMaGBNtQNe/Donor-and-Volunteer-Experience-%2F-Fall20?node-id=2%3A4)
- [x] Create the ReviewStepProps interface (components/donation/form/reducer.ts) with no fields for now. 
- [x] Update the DonationPageForm (components/donation/form/DonationPageForm.tsx) with this new reviewStep in the STEPS list. Also, be sure to update the componentJSX function in the DonationPageForm so that your component actually renders.
- [x] Create a file for the review page component (call it DonationPageFormReviewStep) and put it in components/donation/form and update the DonationPageForm STEPS list to reference this.
- [x] Look at the other steps (i.e. DonationPageFormAmountStep) for inspiration to create a simple form step with just a single textfield displaying dummy information for now.

**Comment by ML-Chen** [comment]
When I press the donate button I'm getting "Couldn't get cardNumber Stripe element!" I'm not sure how to resolve this.
```jsx
// useStripePayment.ts
      const elements = useElements();
      const card = elements.getElement("cardNumber");
      if (!card) {
        throw new Error("Couldn't get cardNumber Stripe element!");
      }
```
![image.png](https://images.zenhubusercontent.com/5d8168cc4def500001d12712/d04d5e7f-7371-421e-b7ea-857023cd3f1c)

**Comment by ML-Chen** [comment]
https://github.com/GTBitsOfGood/gen-soln/tree/michael/166-empty-review-payment

**Comment by PC98** [comment]
Hey, sorry for the late reply.

I suspect what's happening is that the final donation action now occurs in the "Review" step as opposed to the "Payment" step, which rendered the `StripeTextField` element that collected the user's card number, amongst other details. When you go from "Payment" to the "Review" step, all UI/components rendered in the "Payment" steps gets unmounted, so Stripe is unable to get the credit card number.

If this "Review" step is a strict product requirement, I would recommend searching if Stripe Elements offers UI components that can be used for a payment confirmation page. Otherwise, we will have to re-think how the various steps of this form work, perhaps instead of unmounting we can hide the `StripeTextField`s in the background using CSS? (though not sure if this is good practice from a security point of view). We can also abandon usage of the "@stripe/react-stripe-js"  library altogeher and implement our own UI for collecting card information (though I wouldn't recommend this). Let me know if you can think of alternative ways.
