### ISSUE TITLE
[CORE][VMS] Component for non-profit card and corresponding glimmer card

### ISSUE THREAD

**Issue by PC98** [GTBitsOfGood/gen-soln#369]
* Refer to the "Non-profits" page (select this on the left-hand side) of the Figma page for designs of the non-profit card.
* Create a component corresponding to this card. Model the props after the `EventsPageEventCard.tsx` component - have a `onClick` and a data prop. You might have to create a new type to represent this data, refer to how `EventCardData` type is defined.
* Note that while each non-profit will have **a logo image**, we will be using the same background image for each card (see #348 for details). Download the background image from Figma and save it somewhere in `public/`.
* Create a corresponding glimmer/loading card component. Feel free to look at how `EventsPageEventCardGlimmer` has been implemented.
* You will have to use some dummy data to test out the UI. For testing purposes, feel free to render this card as part of one of the event lists, like `EventsPageCauseList.tsx`.

**Comment by matthebrown** [comment]
@kw143 Is there a time later this week that works to pair program on this? If not, we could each take a part of the ticket and work separately. I've started looking into the `NonprofitCard` if you're interested in taking the glimmer.

**Comment by matthebrown** [comment]
@PC98 @kw143 I finished the nonprofit card and pushed the changes to `upstream/matthewbrown/non-profit-card-and-glimmer`. Feel free to work off that for the glimmer component. Gonna refrain from putting up a PR until both parts of the ticket are finished. 
![goodwill_card](https://user-images.githubusercontent.com/45107667/98747860-6874b180-2386-11eb-9cac-eb57f475c5ef.png)
![hearts_card](https://user-images.githubusercontent.com/45107667/98747864-6a3e7500-2386-11eb-846e-ce95a9deb34a.png)

**Comment by PC98** [comment]
@matthewbrown77 This looks awesome!
Feel free to put out a PR though, it's okay if the glimmer isn't ready yet we can still merge your changes and someone else can work on it.

**Comment by kw143** [comment]
Sorry about not responding earlier. I did not realize I was assigned this task again with a different person, and Andrew and I have been working on this separately. I just noticed it because in the pull request I got an error for duplicate nonprofitcarddata type. 

You can always message me on slack, I check it everyday. Sorry about missing this issue again. 
The same work is covered in the pull request I just made. And the cards are already connected to the carousel and with backend data, although it seems like you added the address and supporters, which I did not do, since there was no data to pull from.

**Comment by kw143** [comment]
Will probably switched to use yours later tonight. 

Done
